# Generated by Django 4.0.4 on 2022-05-30 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song', models.FileField(blank=True, upload_to='uploads/songs')),
            ],
            options={
                'verbose_name': 'Песни',
                'verbose_name_plural': 'Песни',
            },
        ),
        migrations.DeleteModel(
            name='Content',
        ),
    ]
